/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: "0px",
      sm: "360px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
    },
    fontFamily: {
      supreme: ["Supreme", "sans-serif"],
      "supreme-italic": ["Supreme Italic", "sans-serif"],
    },
    extend: {
      spacing: {
        "8xl": "96rem",
        "9xl": "128rem",
      },
      borderRadius: {
        "4xl": "2rem",
      },
    },
    colors: {
      transparent: "transparent",
      black: "#000000",
      "black-hover": "#212121",
      white: "#ffffff",
      "white-hover": "#e8e8e8",
      toolight: {
        primary: "#f1c21b",
        "primary-hover-dark": "#ddb00e",
        "primary-hover-darker": "#a8860b",
        "primary-hover-light": "#f8e6a0",
        "primary-active": "#b28600",
        danger: "#da1e28",
        "danger-hover-dark": "#b81922",
        "danger-hover-light": "#fa4d56",
        "danger-active": "#a2191f",
        success: "#24a148",
        "success-hover-dark": "#166f31",
        "success-hover-light": "#3bab5a",
        "success-active": "#0e6027",
        disabled: "#c6c6c6",
        secondary: "#494949",
        "secondary-hover-dark": "#292929",
        "secondary-hover-light": "#393939",
        "secondary-active": "#181818",
        tertiary: "#292929",
        "tertiary-hover-dark": "#292929",
        "tertiary-hover-light": "#393939",
        "tertiary-active": "#161616",
        paragraph: "#161616",
        "paragraph-hover-dark": "#292929",
        "paragraph-hover-light": "#393939",
        "paragraph-active": "#333333",
        "border-gray-dark": "#999999",
        "border-gray-light": "#c6c6c6",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
